

export const GET_TEACHER_SUCCESS='GET_TEACHER_SUCCESS';
export const GET_TEACHER_REQUEST='GET_TEACHER_REQUEST';
export const GET_TEACHER_FAILURE='GET_TEACHER_FAILURE';
export const POST_HEIRE_STATUS='POST_HEIRE_STATUS'